### PR TITLE
🐞 Bug Fixes and 🔄 Dependency Update

### PR DESCRIPTION
**Pull request by misterneo**
Hello, 

I've made some improvements to the code to fix some issues. Here's what's been done:

- Bug Fix: Handling Autocomplete Absence: I've improved the code to handle situations where the autocomplete box doesn't appear (for some reason the hashtag #comedy reproduces the issue!). Now, it adapts gracefully without any disruptions.

- Bug Fix: Smoother Post Button Click: I've enhanced the code by adding exception handling for potential click interception issues when interacting with the post button. I kept getting this error randomly while uploading multiple videos: 

```bach
Message: element click intercepted: Element <iframe src="https://www.tiktok.com/creator#/upload?
scene=creator_center" data-tt="Upload_index_iframe" style="height: 1215px; border-style: none; width: 100%; 
margin-bottom: -7px; z-index: 2; position: relative;" cd_frame_id_="d02cbb98c4608a8e1517f2ac10ea3b80">
</iframe> is not clickable at point (379, 561). Other element would receive the click: <tiktok-cookie-banner locale="en"
user-config-ele-id="tiktok-cookie-banner-config" disabled="false"></tiktok-cookie-banner>
(Session info: headless chrome=117.0.5938.149)
  ```

- Bug Fix: Multiple Video Uploads in upload_videos Function: I've resolved an issue that was causing an error during multi-video uploads within the upload_videos function. [The Issue was described in this comment here.](https://github.com/wkaisertexas/tiktok-uploader/issues/35#issuecomment-1742020651) This was caused by a page reload alert box that blocked the browser and needed to be accepted before renavigating to the upload page again.

- Bug Fix: Chromedriver BMP Character Compatibility: I've fixed an issue related to BMP characters in Chromedriver. It should now skip these characters in case they're present in the description.

- Dependency Update: Added 'pytz' to pyproject.toml: I've included the 'pytz' dependency in the project's 'pyproject.toml' configuration file.

Please take a look and let me know your thoughts.
Thank you.

### CODE REVIEW

**Review by LevaniVashadze — APPROVED** [review]
Great work, i hope it gets merged soon

**Comment by wkaisertexas** [comment]
LGTM. Thank you so much for submitting the PR.

**Comment by misterneo** [comment]
You're welcome, Would it be possible to also push a quick release on PyPi?

**Comment by wkaisertexas** [comment]
Done. I am sorry about that. I forgot I setup the CI to only push when the branch was tagged for release.

**Comment by misterneo** [comment]
Thank you so much 🙏

**Pull request merged**
