### PR TITLE
Fix Upload Issue and black formatter

### PR DESCRIPTION
**Pull request by cateyelow**
tiktok recently removes iframe.

### CODE REVIEW

**Review by wkaisertexas — APPROVED** [review]
Next time do not run the formatter and make changes at the same time. At the very least make them two separate commits

**Comment by cateyelow** [comment]
Thank you for feedback. I'll keep that in mind

**Comment by felipexpert** [comment]
I've tried to use tiktok-uploader from https://github.com/cateyelow/tiktok-uploader.git, I've reinstalled following README instructions, but it is still not uploading videos. Any sugestion?

**Comment by cateyelow** [comment]
@felipexpert please give some logs, it is working to me and others

**Pull request merged**
